import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, Clock3, DatabaseZap } from 'lucide-react';
import { loadDashboard } from '../services/data';
import type { DashboardData } from '../types/market';
import PerformanceBadge from '../components/PerformanceBadge';
import { num, updated } from '../utils/format';
export default function Overview(){
  const [data,setData]=useState<DashboardData|null>(null); const [error,setError]=useState('');
  useEffect(()=>{loadDashboard().then(setData).catch(e=>setError(String(e)))},[]);
  if(error) return <div className="panel p-6 text-rose-500">{error}</div>; if(!data) return <div className="muted p-10">Loading market data…</div>;
  return <div className="space-y-6"><section className="grid gap-4 lg:grid-cols-[1.5fr_.5fr]"><div className="panel p-6"><div className="flex items-start justify-between gap-4"><div><div className="label">Market monitor</div><h1 className="mt-2 text-3xl font-bold tracking-tight">Your ETFs, without broker noise.</h1><p className="mt-2 max-w-2xl muted">Track prices, performance, holdings, sector exposure and approximate holding-level contribution using public market data.</p></div><div className="rounded-2xl bg-slate-100 p-3 dark:bg-slate-900"><Activity/></div></div></div><div className="panel p-6"><div className="flex gap-3"><Clock3 size={18}/><div><div className="label">Last Updated</div><div className="mt-1 font-semibold">{updated(data.generatedAt)}</div><div className="mt-1 text-xs muted">{data.delayNote}</div></div></div></div></section>
  <section className="grid gap-4 lg:grid-cols-3">{data.etfs.map(etf=><Link to={`/etfs/${etf.id}`} key={etf.id} className="panel p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-2"><div><div className="label">{etf.ticker || etf.isin}</div><h2 className="mt-1 font-semibold">{etf.name}</h2><div className="mt-1 text-xs muted">{etf.provider || 'Data unavailable'} · {etf.exchange || 'Data unavailable'}</div></div><DatabaseZap size={18} className="muted"/></div><div className="mt-5 flex items-end justify-between"><div><div className="text-3xl font-bold">{num(etf.price,etf.tradingCurrency)}</div><div className="text-xs muted">{etf.isin}</div></div><PerformanceBadge value={etf.performance.day} label="Today"/></div><div className="mt-5 grid grid-cols-4 gap-3 border-t border-slate-100 pt-4 dark:border-slate-800"><PerformanceBadge value={etf.performance.week} label="1W"/><PerformanceBadge value={etf.performance.month} label="1M"/><PerformanceBadge value={etf.performance.ytd} label="YTD"/><PerformanceBadge value={etf.performance.year} label="1Y"/></div></Link>)}</section>
  <section className="panel overflow-hidden"><div className="border-b border-slate-200 p-5 dark:border-slate-800"><div className="label">Global snapshot</div><h2 className="mt-1 text-xl font-semibold">Markets</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-4">{data.markets.slice(0,8).map(m=><div key={m.id} className="border-b border-slate-100 p-4 sm:border-r dark:border-slate-800"><div className="text-sm font-semibold">{m.name}</div><div className="mt-2 flex items-end justify-between"><span className="text-xl font-bold">{num(m.price,m.currency)}</span><PerformanceBadge value={m.performance.day}/></div></div>)}</div></section>
  {data.warnings.length>0&&<div className="rounded-xl border border-amber-300/50 bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">Some sources failed during the last refresh. Missing values are shown as “Data unavailable”; stale/fake zeros are never substituted.</div>}</div>
}
